In [24]:
import numpy as np

# print(help(np.genfromtxt))
data_1 = np.genfromtxt('world_alcohol.txt',delimiter = ',',dtype='str')
# print(data)
# data2 = data[1;,]
# print(data2)
# print(data[1:,:])

In [18]:
data = np.array([1,2,3,4])
data.shape

(4,)

In [19]:
data2 = np.array([[1,2,3],[4,5,6]])
data2.shape

(2, 3)

In [21]:
number = np.array([1,2,3,4])
print(number)
number.dtype

[1 2 3 4]


dtype('int32')

In [23]:
number = np.array([1,2,3,'4'])
print(number)
number.dtype

['1' '2' '3' '4']


dtype('<U11')

In [25]:
data_1

array([['Year', 'WHO region', 'Country', 'Beverage Types',
        'Display Value'],
       ['1986', 'Western Pacific', 'Viet Nam', 'Wine', '0'],
       ['1986', 'Americas', 'Uruguay', 'Other', '0.5'],
       ...,
       ['1987', 'Africa', 'Malawi', 'Other', '0.75'],
       ['1989', 'Americas', 'Bahamas', 'Wine', '1.5'],
       ['1985', 'Africa', 'Malawi', 'Spirits', '0.31']], dtype='<U52')

In [26]:
vector = np.array([1,2,3,4])
print(vector[0:3])

[1 2 3]


In [27]:
mix = np.array([
    [5,10,15],
    [20,25,30],
    [35,40,45]
])
print(mix[0:2,0:2])

[[ 5 10]
 [20 25]]


In [28]:
vector == 3

array([False, False,  True, False])

In [29]:
mix ==25

array([[False, False, False],
       [False,  True, False],
       [False, False, False]])

In [30]:
mix == 25|30

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [33]:
equal_to_ten = (vector == 3)
print(vector[equal_to_ten])

[3]
