In [24]:
import numpy as np

# print(help(np.genfromtxt))
data_1 = np.genfromtxt('world_alcohol.txt',delimiter = ',',dtype='str')
# print(data)
# data2 = data[1;,]
# print(data2)
# print(data[1:,:])

In [18]:
data = np.array([1,2,3,4])
data.shape

(4,)

In [19]:
data2 = np.array([[1,2,3],[4,5,6]])
data2.shape

(2, 3)

In [21]:
number = np.array([1,2,3,4])
print(number)
number.dtype

[1 2 3 4]


dtype('int32')

In [23]:
number = np.array([1,2,3,'4'])
print(number)
number.dtype

['1' '2' '3' '4']


dtype('<U11')

In [25]:
data_1

array([['Year', 'WHO region', 'Country', 'Beverage Types',
        'Display Value'],
       ['1986', 'Western Pacific', 'Viet Nam', 'Wine', '0'],
       ['1986', 'Americas', 'Uruguay', 'Other', '0.5'],
       ...,
       ['1987', 'Africa', 'Malawi', 'Other', '0.75'],
       ['1989', 'Americas', 'Bahamas', 'Wine', '1.5'],
       ['1985', 'Africa', 'Malawi', 'Spirits', '0.31']], dtype='<U52')

In [26]:
vector = np.array([1,2,3,4])
print(vector[0:3])

[1 2 3]


In [27]:
mix = np.array([
    [5,10,15],
    [20,25,30],
    [35,40,45]
])
print(mix[0:2,0:2])

[[ 5 10]
 [20 25]]


In [28]:
vector == 3

array([False, False,  True, False])

In [29]:
mix ==25

array([[False, False, False],
       [False,  True, False],
       [False, False, False]])

In [30]:
mix == 25|30

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [33]:
equal_to_ten = (vector == 3)
print(vector[equal_to_ten])

[3]


In [35]:
equal_to_10_or_25 = (mix == 10)|(mix==25)
print(equal_to_10_or_25)

[[False  True False]
 [False  True False]
 [False False False]]


In [36]:
mix[equal_to_10_or_25]

array([10, 25])

In [37]:
vect = np.array(
['1','2','3','4'])
print(vect)

['1' '2' '3' '4']


In [38]:
vect = vect.astype(int)
print(vect)

[1 2 3 4]


In [39]:
mix.sum(axis=1)

array([ 30,  75, 120])

In [40]:
mix.sum(axis=0)

array([60, 75, 90])

In [41]:
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [42]:
a = a.reshape(3,5)

In [43]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [44]:
a.shape

(3, 5)

In [45]:
a.ndim

2

In [46]:
a.size

15

In [47]:
print(np.zeros([3,4]))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [48]:
np.ones((2,3,4), dtype = 'int')

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [50]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [51]:
np.random.random((2,3))

array([[0.92482662, 0.1626358 , 0.06503679],
       [0.26879183, 0.72681943, 0.31086171]])

In [52]:
np.linspace(0, 2*(np.pi), 100)

array([0.        , 0.06346652, 0.12693304, 0.19039955, 0.25386607,
       0.31733259, 0.38079911, 0.44426563, 0.50773215, 0.57119866,
       0.63466518, 0.6981317 , 0.76159822, 0.82506474, 0.88853126,
       0.95199777, 1.01546429, 1.07893081, 1.14239733, 1.20586385,
       1.26933037, 1.33279688, 1.3962634 , 1.45972992, 1.52319644,
       1.58666296, 1.65012947, 1.71359599, 1.77706251, 1.84052903,
       1.90399555, 1.96746207, 2.03092858, 2.0943951 , 2.15786162,
       2.22132814, 2.28479466, 2.34826118, 2.41172769, 2.47519421,
       2.53866073, 2.60212725, 2.66559377, 2.72906028, 2.7925268 ,
       2.85599332, 2.91945984, 2.98292636, 3.04639288, 3.10985939,
       3.17332591, 3.23679243, 3.30025895, 3.36372547, 3.42719199,
       3.4906585 , 3.55412502, 3.61759154, 3.68105806, 3.74452458,
       3.8079911 , 3.87145761, 3.93492413, 3.99839065, 4.06185717,
       4.12532369, 4.1887902 , 4.25225672, 4.31572324, 4.37918976,
       4.44265628, 4.5061228 , 4.56958931, 4.63305583, 4.69652

In [56]:
A = np.array([[1,1],[0,1]])
B = np.array([[1,2],[3,4]])
print(A)
print('-----------')
print(B)
print('-----------')
print(A*B)
print('-----------')
print(A.dot(B))
print('-----------')
print(np.dot(A,B))

[[1 1]
 [0 1]]
-----------
[[1 2]
 [3 4]]
-----------
[[1 2]
 [0 4]]
-----------
[[4 6]
 [3 4]]
-----------
[[4 6]
 [3 4]]


In [62]:
a = np.floor(10*np.random.random((3,4)))
print(a)
print(a.ravel())
print(a.T)

[[6. 2. 1. 6.]
 [7. 2. 5. 1.]
 [8. 4. 1. 6.]]
[6. 2. 1. 6. 7. 2. 5. 1. 8. 4. 1. 6.]
[[6. 7. 8.]
 [2. 2. 4.]
 [1. 5. 1.]
 [6. 1. 6.]]


In [65]:
a = np.floor(10*np.random.random((2,2)))
b = np.floor(10*np.random.random((2,2)))
print(a)
print('--------')
print(b)
print('--------')
print(np.hstack((a,b)))
print('--------')
print(np.vstack((a,b)))

[[3. 3.]
 [0. 3.]]
--------
[[0. 6.]
 [0. 9.]]
--------
[[3. 3. 0. 6.]
 [0. 3. 0. 9.]]
--------
[[3. 3.]
 [0. 3.]
 [0. 6.]
 [0. 9.]]


In [68]:
a = np.floor(10*np.random.random((2,12)))
print(a)
print('----------')
print(np.hsplit(a,3))
print('----------')
print(np.hsplit(a,(3,5)))

[[5. 3. 1. 9. 5. 0. 9. 7. 7. 7. 7. 6.]
 [8. 6. 8. 3. 2. 8. 4. 8. 3. 1. 7. 0.]]
----------
[array([[5., 3., 1., 9.],
       [8., 6., 8., 3.]]), array([[5., 0., 9., 7.],
       [2., 8., 4., 8.]]), array([[7., 7., 7., 6.],
       [3., 1., 7., 0.]])]
----------
[array([[5., 3., 1.],
       [8., 6., 8.]]), array([[9., 5.],
       [3., 2.]]), array([[0., 9., 7., 7., 7., 7., 6.],
       [8., 4., 8., 3., 1., 7., 0.]])]


In [69]:
b = a.T
print(b)
print('-----------')
print(np.vsplit(b,3))

print('-----------')
print(np.vsplit(b,(3,5)))

[[5. 8.]
 [3. 6.]
 [1. 8.]
 [9. 3.]
 [5. 2.]
 [0. 8.]
 [9. 4.]
 [7. 8.]
 [7. 3.]
 [7. 1.]
 [7. 7.]
 [6. 0.]]
-----------
[array([[5., 8.],
       [3., 6.],
       [1., 8.],
       [9., 3.]]), array([[5., 2.],
       [0., 8.],
       [9., 4.],
       [7., 8.]]), array([[7., 3.],
       [7., 1.],
       [7., 7.],
       [6., 0.]])]
-----------
[array([[5., 8.],
       [3., 6.],
       [1., 8.]]), array([[9., 3.],
       [5., 2.]]), array([[0., 8.],
       [9., 4.],
       [7., 8.],
       [7., 3.],
       [7., 1.],
       [7., 7.],
       [6., 0.]])]


In [78]:
a = np.array([2,1,4,3])
# a.sort()
# print(a)
c = np.argsort(a)
print(c)

[1 0 3 2]


In [75]:
b = np.array([[2,1,3,4],
             [3,5,6,4],
             [1,4,7,2]])
b.sort(axis=0)
print(b)

[[1 1 3 2]
 [2 4 6 4]
 [3 5 7 4]]
